"""add skill_taxonomy table and canonical_skill_id

Revision ID: 2c54ded07cc9
Revises: efee2cccf170
Create Date: ...

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '2c54ded07cc9'
down_revision: Union[str, Sequence[str], None] = 'efee2cccf170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_taxonomy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.add_column('skill_scores', sa.Column('canonical_skill_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'skill_scores', 'skill_taxonomy', ['canonical_skill_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skill_scores', type_='foreignkey')
    op.drop_column('skill_scores', 'canonical_skill_id')
    op.drop_table('skill_taxonomy')
    # ### end Alembic commands ###
