"""add assistant_name to user_preferences

Revision ID: 57a4278707d1
Revises: 60bbd9292c03
Create Date: 2026-09-02 00:40:23.460042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a4278707d1'
down_revision: Union[str, Sequence[str], None] = '60bbd9292c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('assistant_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'assistant_name')
    # ### end Alembic commands ###
