"""add github_access_token to users

Revision ID: 7f25fed2cc27
Revises: 52207d9eefeb
Create Date: 2026-08-02 00:46:16.651013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f25fed2cc27'
down_revision: Union[str, Sequence[str], None] = '52207d9eefeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_access_token')
    # ### end Alembic commands ###
